#!/usr/bin/env python3
from pathlib import Path
import html,re

ROOT=Path(__file__).resolve().parents[2]
START='<!-- NEXUSNOVA_ARTICLE_VALUE_START -->'
END='<!-- NEXUSNOVA_ARTICLE_VALUE_END -->'
DATA={
'articles/ai-photo-restoration-vs-enhancement.html':{
'a':'Photo restoration is easiest to judge when the original scan or camera file stays untouched. Work on a copy, compare every major edit with the source and separate visible cleanup from any AI-generated reconstruction. Dust removal, contrast correction and careful sharpening can preserve evidence from the original pixels, while face reconstruction or texture synthesis may add plausible detail that was never captured.',
'b':'A practical test is to restore one difficult area at a time. For an old portrait, first correct exposure and color, then inspect eyes, teeth, hair edges and text in the background before enabling stronger generative repair. If the new version suddenly contains crisp eyelashes, jewellery or letters that are not supported by the source, label that result as an interpretation rather than recovered fact.',
'c':'Keep at least three versions: the untouched original, a conservative restoration and any aggressive AI version. This makes it possible to show which changes are photographic cleanup and which are inferred. For family archives, legal evidence, historical images or identity-sensitive material, preserving that distinction matters more than making every area look perfectly sharp.',
'd':'Upscaling can make an image easier to display or print, but it does not prove that newly visible texture is authentic. A larger file may simply contain interpolated or generated pixels. Compare the restored image at normal viewing size and at 100% zoom, and avoid using an AI-restored face as the only source for identification or documentation.',
'e':'The useful takeaway is to define the goal before choosing the tool: improve readability, repair damage, prepare a print, or create an artistic reconstruction. Each goal allows a different amount of intervention, and the safest workflow always keeps the original available for comparison.'},
'articles/amd-adrenalin-26-8-1-modern-warfare-4.html':{
'a':'Driver release notes are useful only when the exact package, GPU family and game build match the system being tested. Before updating, record the current Adrenalin version, Windows build, GPU model and any custom tuning so a later improvement or regression can be traced to a specific change instead of guesswork.',
'b':'If the article mentions a game fix, reproduce the original problem before changing several variables at once. Update the driver, reboot if required, keep the same graphics settings and test the same scene or benchmark. If the issue disappears, that is stronger evidence than changing the driver, game settings, overlays and background software simultaneously.',
'c':'A new driver is not automatically the best choice for every stable PC. Competitive players or production systems may prefer to wait until the game or driver has been tested on similar hardware, while users affected by a documented issue may have a clearer reason to update. Keep the previous installer or know how to roll back if a regression appears.',
'd':'Do not treat a crash that occurs after an update as proof that the GPU driver is the sole cause. Shader compilation, game patches, anti-cheat, overlays, unstable overclocks, RAM errors and Windows changes can produce similar symptoms. Event logs and repeatable tests help narrow the cause without random registry edits.',
'e':'For any version-specific driver article, the safest final check is the vendor release note itself. Use NexusNova as a readable summary, then confirm the package number, supported hardware and known issues on AMD’s official page before changing a working system.'},
'articles/background-removal-online-guide.html':{
'a':'Background removal quality is mostly an edge problem. Hair, fur, transparent objects, motion blur, glass and shadows are harder than a clean product photographed against a plain wall. Judge the cutout against both a light and dark background because small halos can disappear on one color and become obvious on another.',
'b':'For product images, check whether the subject needs a natural contact shadow or a completely transparent floor. Removing every shadow can make a product look like it is floating, while leaving a colored fringe from the original background can look unprofessional on a marketplace listing. Zoom in on logos, straps, fingers and thin edges before exporting.',
'c':'Privacy matters when the source photo contains faces, documents or a home interior. Prefer local processing when the tool genuinely performs the operation in the browser, and read the page’s privacy note before uploading sensitive images to any cloud service. A background remover can hide surroundings in the final image without deleting copies that may already exist elsewhere.',
'd':'Transparent PNG is usually the safest delivery format when the cutout will be placed on different backgrounds. JPG cannot preserve transparency, so it forces an opaque background. If file size matters, compare PNG and WebP support in the destination instead of converting automatically to JPEG.',
'e':'A good workflow is capture or select the cleanest source, remove the background, inspect the mask, fix edge mistakes, then export a copy while keeping the original. AI is helpful for difficult masks, but a simple crop or solid-background photo can sometimes produce a cleaner result with fewer artifacts.'},
'articles/cs2-valorant-sensitivity-edpi-guide.html':{
'a':'Sensitivity conversion starts with a reproducible baseline. Record mouse DPI, current in-game sensitivity, raw-input settings and any acceleration before changing anything. If the DPI is unknown or Windows acceleration is affecting one game, a mathematically correct conversion can still feel different in practice.',
'b':'eDPI is useful inside a comparable sensitivity system because it combines DPI and the game sensitivity value. It does not automatically normalize field of view, zoom behavior, engine rotation scale or scoped multipliers. That is why two equal-looking eDPI numbers from different games are not proof of identical physical mouse movement.',
'c':'After converting a CS2 sensitivity to a Valorant starting value, test it in a practice range rather than immediately changing multiple aim settings. Use the same mouse grip and a simple repeatable motion such as a comfortable 180-degree turn, then adjust in small steps if the new game’s visual scale or mechanics feel different.',
'd':'Do not chase professional-player settings as if they were universal targets. Desk space, monitor size, role, posture and personal control all matter. A lower sensitivity can make fine corrections easier for one player while becoming tiring or impractical for another.',
'e':'Keep the old settings written down and change only one variable at a time. The calculator provides a starting point; the final value should be chosen through consistent testing, not by assuming a formula can perfectly reproduce muscle memory across different games.'},
'articles/emi-calculator-explained.html':{
'a':'EMI is only one view of a loan. Two offers can have similar monthly payments but very different total repayment because the interest rate, tenure, fees, insurance or compounding method differs. When comparing loans, write down principal, rate, term, monthly payment, total interest and any mandatory charges together.',
'b':'A longer tenure usually reduces the scheduled monthly burden because the principal is spread across more instalments, but it can increase the amount paid over time. Run the same principal and rate with two different tenures to see that trade-off instead of deciding from the smallest monthly number alone.',
'c':'The calculator formula assumes the inputs match its stated convention. A lender may use a different day-count method, rounding rule, variable rate, balloon payment or fee structure. The official repayment schedule and contract therefore remain the final source for an actual financing decision.',
'd':'Before signing, test a realistic budget rather than the maximum amount a calculator says is affordable. Include existing obligations, emergency savings and the possibility that variable household costs rise. A mathematically manageable EMI can still be financially uncomfortable when the rest of the budget is ignored.',
'e':'Use the NexusNova calculator to understand the mechanics and compare scenarios, then reconcile the result with the lender’s written schedule. If the numbers do not match, identify which assumption is different before accepting either result.'},
'articles/google-preferred-sources-2026.html':{
'a':'A feature that lets users express source preferences should not be confused with a universal ranking guarantee. Publishers still need useful original pages, clear authorship, accessible navigation and technically crawlable content. A preference control cannot compensate for thin pages or duplicate material that gives a searcher little reason to stay.',
'b':'When evaluating any Google search feature, separate three questions: what Google officially documents, where the feature is available, and what independent site owners are actually observing. Screenshots or third-party commentary can be useful context, but they should not be presented as a broader ranking rule unless Google states that relationship.',
'c':'For a smaller publisher, the practical response is to make the site worth selecting as a source. That means publishing focused explanations, correcting outdated claims, using descriptive titles, keeping pages fast and making the relationship between the publisher and the content transparent. These improvements help users even if a particular search feature changes later.',
'd':'Avoid aggressive popups or copy that promises “prefer us and rank us higher.” A source preference is a user choice, not a shortcut around search-quality systems. If NexusNova offers a button or tutorial for the feature, the wording should explain exactly what the user is doing and avoid implying a guaranteed SEO benefit.',
'e':'For time-sensitive search-product articles, keep a dated source section and recheck the official documentation before major edits. Search interfaces change quickly, so an article should make it easy to distinguish the documented feature from NexusNova’s interpretation and practical publishing advice.'},
'articles/gpt-5-6-sol-context-window-guide.html':{
'a':'A context-window number describes how much tokenized information a model configuration can accept or work with under the documented limits; it is not the same as a word count, memory of every prior chat, or a promise that every product interface exposes the same maximum. Tokenization, system instructions, tools and output allowance all affect the usable space.',
'b':'For a long document workflow, estimate tokens before uploading everything. Split material by task, keep the most relevant sections together and avoid repeating the same appendix or boilerplate in every request. A very large context can be useful, but adding irrelevant text can still make retrieval and verification harder.',
'c':'The output limit matters separately from the input limit. A model may be able to read a large corpus while still returning a much smaller answer. Plan extraction or analysis in stages when the desired output itself is long, and save intermediate structured results instead of asking one response to reproduce an entire source collection.',
'd':'Model names and limits can differ between ChatGPT configurations and API models. Before building a production workflow around a specific number, check the current OpenAI documentation or product information for the exact model and interface you intend to use. Do not assume a headline limit applies everywhere.',
'e':'Treat long context as capacity, not automatic accuracy. Ask for citations to the supplied material, verify important numbers against the source and use smaller targeted prompts when a decision depends on one section. Better organization often improves reliability more than simply filling the maximum window.'},
'articles/hex-vs-rgb-colors.html':{
'a':'HEX and RGB usually describe the same red, green and blue channel values in different notation. Converting between them should preserve the encoded color when the values are equivalent, but the appearance on a real display still depends on brightness, calibration, color profile and surrounding colors.',
'b':'A useful debugging habit is to convert one known color in both directions. RGB 255, 0, 0 corresponds to #FF0000, so if a design tool shows something visibly different after conversion, the issue is more likely to be opacity, color management or another CSS effect than the basic conversion itself.',
'c':'Alpha or transparency is a separate concern. Standard six-digit HEX expresses RGB channels, while some CSS formats can include alpha as additional information. When copying a brand color, make sure you are not accidentally changing opacity or compositing it over a different background.',
'd':'For web accessibility, the code format does not tell you whether text has enough contrast. Compare the foreground and background combination using an appropriate contrast checker and test interactive states such as hover, disabled and focus styles.',
'e':'Use HEX or RGB according to the tool and workflow rather than treating one as more accurate. Keep the canonical brand values documented, convert when necessary and verify the final rendered component in the actual browser or design environment.'},
'articles/modern-warfare-4-beta-pc-checklist.html':{
'a':'A beta checklist should separate official schedule information from practical PC preparation. Confirm the current beta dates and platform requirements from the publisher before downloading, because schedules and access windows can change. Keep the source link beside the date instead of relying on an old social post or screenshot.',
'b':'Before launching, record GPU driver version, Windows build, available storage and the graphics preset you plan to test. Close unnecessary overlays or monitoring tools only if you are troubleshooting a conflict; changing everything at once makes it difficult to learn which factor affected a crash or performance issue.',
'c':'Beta performance is not a final benchmark for the released game. Shader compilation, server load, debug code, unfinished optimization and later patches can all change the experience. Use the beta to test basic compatibility and settings, but avoid making an expensive hardware purchase from one temporary build unless the requirement is confirmed elsewhere.',
'd':'If the game crashes, reproduce the issue with stock CPU/GPU settings before blaming the newest driver or Windows update. Save the error message, event-log entry and exact scene or action that triggers the problem. Repeatable evidence is more useful than random registry tweaks or unverified “FPS boost” scripts.',
'e':'Keep the article’s patch-note section dated. When a new beta update appears, add the new source rather than rewriting old observations as if they were always true. That makes the page useful to readers who need to understand what changed between tests.'},
'articles/pomodoro-focus-workflow.html':{
'a':'Pomodoro works best when the timer is attached to a clearly defined task. “Work for 25 minutes” is vague; “draft the first two sections of the report” gives the interval a finish condition. Write the task before starting so the timer does not become another screen to manage.',
'b':'The classic interval is a starting point, not a rule. Deep technical work may need a longer uninterrupted block, while a difficult or avoided task may benefit from a shorter first interval. Change one timing variable at a time and keep the break separate from the work itself.',
'c':'During a session, capture interruptions in a short note instead of immediately switching tasks. At the end of the interval, decide whether each interruption deserves action. This preserves focus without relying on memory and prevents a small notification from turning into a long detour.',
'd':'Use breaks for physical and mental separation: stand up, drink water or look away from the screen. Opening another demanding feed or work chat can keep the brain inside the same task even if the timer says “break.”',
'e':'Judge the workflow by completed useful work, not by the number of Pomodoro sessions accumulated. If the timer repeatedly breaks concentration, adjust it. A productivity technique is successful when it reduces friction around the real task, not when the technique itself becomes the goal.'},
'articles/resume-mistakes-to-fix.html':{
'a':'The strongest resume fixes come from the target job, not from decorative formatting. Read the job description, identify the skills and outcomes that genuinely match your experience, then make those relevant facts easy to find near the top of the document. Do not add keywords for work you have never done.',
'b':'Replace vague duties with evidence where possible. “Responsible for customer support” tells the reader very little; a stronger line can explain the type of customers, volume, tools used or measurable outcome if those facts are true. Numbers should clarify impact, not be invented to make a bullet look impressive.',
'c':'Keep layout simple enough to survive PDF export and ordinary applicant-tracking systems. Use clear headings, readable fonts, consistent dates and normal text for important information. Essential details placed only inside graphics, icons or unusual columns can become harder to parse or skim.',
'd':'Tailor without rewriting your entire history for every application. Keep a master resume with all verified experience, then create a focused version that emphasizes the most relevant items. This reduces the risk of inconsistent dates or accidental exaggeration across applications.',
'e':'Before sending, check the final PDF rather than only the editor. Open it on another device, verify links, page breaks, contact details and filename, and confirm that the document still looks professional when printed or viewed at 100% zoom.'},
'articles/simple-invoice-checklist-guide.html':{
'a':'An invoice is easier to dispute or delay when basic identifiers are missing. Clearly show the seller, customer, invoice number, issue date, line items, currency and total. If the business is subject to tax-registration or statutory invoice rules, include the fields required by that jurisdiction rather than copying a generic template blindly.',
'b':'Review every line item against the actual agreement or delivery record. Quantity, unit price, discount and tax should match the terms the customer accepted. If a service is billed by milestone or time period, use a description that lets both sides understand what the charge covers without opening a separate conversation.',
'c':'Check the math from subtotal to final amount and make the payment terms unambiguous. A due date is clearer than “pay soon,” and bank or payment instructions should be copied from a trusted record. Do not place full card details, passwords or sensitive authentication information inside an invoice.',
'd':'Use a consistent numbering system that helps you locate the invoice later. The sequence does not need to expose confidential business volume, but it should be unique enough to avoid two different customers receiving documents with the same identifier.',
'e':'Finally, inspect the exported PDF. Make sure the company name, customer, total and payment information are not cut off, fonts render correctly and the file opens without requiring an editor. Keep your source records even after the invoice has been sent.'},
'articles/split-pdf-organize-pages.html':{
'a':'PDF page numbers can be confusing because the printed label inside a report may not match the viewer’s numeric page position. A cover can be file page 1 while the document itself calls the next page “1.” Confirm the viewer positions before entering a range so the wrong section is not extracted.',
'b':'Keep the source PDF untouched and give the extracted file a descriptive name that explains what it contains. If several ranges are being created, use a consistent naming pattern with document name, section and date so the files can be put back into the correct order later.',
'c':'After splitting, reopen the new PDF and check the first page, last page, total page count and orientation. If the source contains forms, bookmarks, links, attachments or digital signatures, verify those features separately because page extraction can change how they behave.',
'd':'Splitting is often safer than converting pages to images when the goal is simply to share part of a document. Image conversion can reduce text searchability, accessibility and vector quality, while a PDF page extraction can preserve more of the original document structure.',
'e':'If the selected pages will later be merged into another document, plan the final order before creating many small files. A simple page list written first can prevent missing or duplicated pages in a larger submission.'},
'articles/typing-speed-wpm-accuracy-guide.html':{
'a':'Typing speed scores are only comparable when the test conditions are similar. Text difficulty, test duration, keyboard layout, device latency and the way errors are counted can all change the result. Use the same test and hardware when measuring your own progress over time.',
'b':'WPM without accuracy can be misleading. If a faster attempt produces many corrections, the practical output may be worse than a slightly slower clean attempt. Track both speed and error rate and aim for stable accuracy before forcing higher tempo.',
'c':'Practice short weak patterns rather than repeatedly taking full tests. If numbers, punctuation or certain letter combinations cause most mistakes, isolate them for a few minutes and return to normal passages afterward. This makes practice more targeted without turning every session into a score chase.',
'd':'Posture and fatigue matter. Keep wrists neutral, use a comfortable keyboard position and stop if repeated practice causes pain or numbness. A browser typing test is a training aid, not a medical or ergonomic assessment.',
'e':'For job or school requirements, use the assessment method specified by the organization. NexusNova can provide a personal baseline, but another platform may use a different text set, correction rule or WPM formula.'},
'articles/unix-timestamps-explained.html':{
'a':'A Unix timestamp represents an instant relative to the Unix epoch, while the human-readable date you see depends on how software interprets the unit and time zone. The first debugging question should therefore be whether the source is using seconds, milliseconds, microseconds or another scale.',
'b':'When checking an API value, convert it to UTC first and keep the original number visible. If the UTC result is correct but the local display is wrong, the problem is probably time-zone handling rather than the stored instant itself. This distinction prevents developers from “fixing” correct data with manual offsets.',
'c':'Daylight-saving time is a presentation rule, not something that should usually be baked into a Unix timestamp. Use a named time zone when converting a future or historical instant because a fixed UTC offset may not represent the applicable rule on that date.',
'd':'Negative timestamps and dates far in the future can expose library or platform limits, while JavaScript and databases can have different precision behavior. Test the exact environment used by the application instead of assuming every system supports the same range.',
'e':'In logs, store the raw timestamp and enough context to reconstruct the event. A human-readable local date is useful for display, but the original numeric value and UTC interpretation are easier to compare across servers and regions.'},
'articles/windows-11-august-2026-rgb-gaming-crashes.html':{
'a':'When a gaming crash appears after a Windows update, start by confirming the exact Windows build and the software or driver version involved. Similar symptoms reported online do not prove the same root cause on every PC. Save the event-log entry or error code before making changes.',
'b':'If RGB or peripheral software is suspected, test in a controlled way: return CPU and GPU clocks to stock, update or temporarily disable one vendor utility, reboot and reproduce the same game scene. Avoid uninstalling several drivers and editing the registry simultaneously because that destroys the evidence needed to isolate the problem.',
'c':'Check Microsoft and the hardware vendor for a documented known issue or fixed build. Community reports can help identify patterns, but an official acknowledgement or release note is stronger evidence for a version-specific article. Keep the date and affected build visible when summarizing the issue.',
'd':'A clean boot or separate Windows user profile can help determine whether a background utility is involved, but important systems should be backed up before deeper troubleshooting. Do not download unknown “fix packs” or modified system files from random video descriptions.',
'e':'If the PC is stable except for one game, also consider the game patch, anti-cheat, overlay, shader cache and corrupted files. The goal is to narrow the fault domain, not to assign blame to the newest component merely because its date is easy to see.'},
'articles/youtube-thumbnail-size-guide-2026.html':{
'a':'Thumbnail guidance should start with the platform’s current official recommendation and then explain why creators may encounter older or alternate dimensions in practice. A larger source can provide more editing headroom, but the final image still needs the correct aspect ratio, supported format and acceptable file size for the upload path.',
'b':'Design at a clear 16:9 composition for standard video thumbnails unless the platform documentation for the specific surface says otherwise. Keep important text and faces away from edges where UI overlays or cropping can reduce visibility, and preview the image at small mobile size before deciding that fine details are readable.',
'c':'A missing max-resolution thumbnail URL does not necessarily mean a video is broken. Availability can depend on how YouTube generated assets for that video. A downloader should show which sizes actually exist rather than promising every resolution for every ID.',
'd':'Do not copy another creator’s thumbnail simply because the image URL is publicly accessible. Public delivery is not a license to republish. Use your own artwork or material you have permission to use, and preserve source files so future edits do not depend on repeatedly downloaded compressed copies.',
'e':'For a final upload, verify the current YouTube Help guidance, inspect the result on desktop and mobile, and keep the title/thumbnail relationship truthful. A high-resolution image cannot compensate for misleading presentation.'},
'guides/ai-prompting.html':{
'a':'A strong prompt begins with the task in plain language. State what you want produced, who it is for and what facts or source material must be used. Avoid adding a long fictional role unless that role changes the expertise, tone or constraints needed for the answer.',
'b':'Context is useful when it changes the result. Give the model the relevant document excerpt, definitions, examples or data schema, but remove unrelated history that makes the instruction harder to follow. For long inputs, label sections so the model can refer to them clearly.',
'c':'Constraints should prevent avoidable mistakes: output length, format, prohibited assumptions, citation requirements and what to do when information is missing. Asking the model to say “not found in the supplied material” is often safer than encouraging it to fill gaps confidently.',
'd':'Verification belongs in the workflow, not in a request for hidden reasoning. Ask for source references, calculations that can be checked, test cases or a concise explanation of assumptions. Then compare important claims with the original source rather than accepting polished wording as proof.',
'e':'Do not paste passwords, private keys or confidential personal data into an AI service without understanding the provider’s data policy and your organization’s rules. A better prompt should improve the task while exposing only the information actually needed.'},
'guides/image-compression.html':{
'a':'Start image compression with the destination requirement. A 4000-pixel photo displayed at 800 pixels wide may waste more bytes through unnecessary dimensions than through a slightly high JPEG quality setting. Resize a copy to a sensible display size before aggressively lowering quality.',
'b':'Compression and resizing solve different problems. Resizing changes pixel dimensions; lossy compression changes how image detail is encoded. Apply the smallest combination that meets the upload or performance target and keep the original as the master file.',
'c':'Photographs tolerate different settings from screenshots, logos and text-heavy graphics. Inspect faces, gradients, small lettering and sharp edges at normal viewing size. Block artifacts or halos that look minor in a large preview can become distracting in a UI icon or product image.',
'd':'Compare file formats only in the destination that will use them. WebP or AVIF can be efficient for modern web delivery, while a specific form may require JPG or PNG. Transparency and metadata can also change during export, so compatibility is more than file extension.',
'e':'Record dimensions, format and final file size before replacing a production asset. If the visual difference is hard to notice but the size reduction is large, the compression is probably useful. If text or brand edges degrade, back off even if the byte count looks attractive.'},
'guides/jpg-to-pdf.html':{
'a':'JPG-to-PDF conversion packages images as document pages; it does not automatically turn photographed text into searchable text. If OCR, selectable text or accessibility tagging is required, use a workflow that explicitly provides those features rather than assuming the PDF container creates them.',
'b':'Put the images in the correct order before generating the PDF and check orientation for each page. Receipts and phone scans are often rotated differently, so a quick visual sort can prevent a final document with upside-down or misplaced pages.',
'c':'Image resolution affects readability, while page dimensions affect how the image is placed on paper. A very large photo can still print poorly if the source is blurry, and an unnecessarily high-resolution image can create a huge PDF without adding useful detail.',
'd':'For sensitive documents, understand where processing occurs. If the tool works locally, the page should state that accurately; if a cloud service is involved, review its privacy policy before uploading identity documents, medical records or confidential business material.',
'e':'After export, reopen the PDF and check first page, last page, page count and zoomed text. Keep the original images until the document has been accepted or archived successfully.'},
'guides/password-security.html':{
'a':'The biggest password improvement is uniqueness. A long password reused on email, shopping and social accounts still creates a chain reaction when one service is breached. Use a different credential for every important account and let a reputable password manager remember them.',
'b':'Length and unpredictability matter more than clever personal substitutions. Replacing letters in a familiar phrase with obvious symbols does not make a reused pattern truly random. Generated passwords or long unique passphrases reduce the need to invent memorable variations yourself.',
'c':'Add multi-factor authentication or passkeys where supported, especially on email and recovery accounts. Recovery channels are part of the security boundary: an attacker who can reset the password through an old phone number or compromised inbox may bypass a strong password entirely.',
'd':'Phishing and malware can defeat password strength by stealing a credential after you type it. Check the domain before signing in, keep devices updated and avoid entering passwords after following unexpected links. A password checker cannot certify that the surrounding login flow is trustworthy.',
'e':'Keep backup and recovery options current and test that you can regain access without exposing recovery codes publicly. Security is a system of layers; the password is important, but it is not the only layer that needs maintenance.'},
'guides/percentage-basics.html':{
'a':'Every percentage calculation has a base value. Before pressing calculate, say the question in words: “15 percent of 80,” “what percent is 12 of 80,” or “how much did 80 change to 100?” These are different formulas even though the same numbers may appear.',
'b':'For a percentage of a number, convert the percentage to a decimal and multiply by the base. For percentage change, subtract old from new and divide by the old value. Writing the base beside the formula prevents many sign and denominator mistakes.',
'c':'Percentage points are different from percent change. If a rate moves from 20% to 25%, the increase is 5 percentage points, while the relative increase is 25% compared with the original 20% rate. Reports should state which interpretation is intended.',
'd':'Zero can make a percentage-change formula undefined because there is no nonzero starting base to divide by. In those cases, describe the absolute change or use the convention required by the real report instead of forcing an infinite-looking percentage into a chart.',
'e':'Keep extra precision during intermediate steps and round only when the final context requires it. Prices, taxes and statistics can use different rounding rules, so the governing document or institution should decide the final format.'},
'guides/resume-writing.html':{
'a':'Start from the job you are applying for, not from a decorative template. Identify the experience, tools and outcomes that genuinely match the role, then make those facts easy to scan. A recruiter should not need to read every line to understand your most relevant evidence.',
'b':'Use a simple heading with accurate contact details and a concise summary only when it adds information. Phrases such as “hard-working professional” are weak without evidence; a stronger summary can name the role, experience area and the type of result you have actually delivered.',
'c':'Experience bullets should explain action and outcome where possible. Use numbers only when they are real and meaningful. If no trustworthy metric exists, describe scale, responsibility or improvement honestly rather than inventing percentages to make the resume look more impressive.',
'd':'Keep skills aligned with evidence elsewhere in the document. A long keyword list that contains technologies never used in work, study or projects can create awkward interview questions and undermine trust. Group related skills so important ones are visible without turning the section into a wall of text.',
'e':'Export to PDF, reopen the file and check links, dates, spacing and filename. Keep a master resume with complete history, then create focused versions for applications so you can tailor emphasis without introducing inconsistent facts.'},
'guides/unit-conversion.html':{
'a':'Unit conversion begins by identifying the physical quantity. Metres and feet can be converted because both measure length; litres and kilograms cannot be converted without additional information such as density. Writing the quantity beside the value prevents meaningless conversions.',
'b':'For scale-based units, convert through a known base or use an exact factor. Metric prefixes are especially convenient: kilometres to metres multiply by 1000, while metres to kilometres divide by 1000. Keep the unit label in every intermediate step so direction errors are obvious.',
'c':'Temperature is different because Celsius and Fahrenheit have an offset as well as a scale. A single multiplication factor is not enough. Use the full formula and confirm whether the task needs an absolute temperature or a temperature difference.',
'd':'Digital storage can use decimal and binary conventions. A manufacturer may use powers of 1000 while an operating system reports values related to powers of 1024. Compare the underlying bytes when a capacity discrepancy matters instead of assuming one side is wrong.',
'e':'For engineering, medical or regulated work, preserve significant figures and follow the unit definitions required by the governing standard. A general converter is useful for arithmetic, but the official standard decides precision and rounding.'},
'tech/ai-agent-browser-security.html':{
'a':'Browser agents are more powerful than ordinary chat because they may be able to click, type, read page content or call connected tools. That means permission boundaries matter more. Give an agent only the accounts and actions required for the task and keep destructive or financial actions behind an explicit confirmation step.',
'b':'Prompt injection can arrive through untrusted page content, documents or messages that try to redirect the agent away from the user’s real instruction. Treat external content as data, not authority. An agent should not reveal secrets, change security settings or follow hidden instructions simply because a webpage tells it to.',
'c':'For high-risk actions, bind approval to the exact operation: which account, amount, file, recipient or deployment is being changed. A generic “continue” confirmation is weaker than showing the user the concrete action immediately before execution.',
'd':'Use separate browser profiles or scoped credentials when possible, keep session access short-lived and review logs after important automated work. If a workflow does not need email, cloud storage or payment access, do not connect those systems “just in case.”',
'e':'AI agents can still be useful when the task is bounded and reviewable. The goal is not to avoid automation; it is to design the workflow so an unexpected page or model mistake cannot silently become a privileged action.'},
'tech/browser-ai-webgpu-webassembly.html':{
'a':'WebAssembly and WebGPU can move more computation into the browser, but developers should treat device capability as variable. Feature-detect support, provide fallbacks and test on low-memory phones as well as powerful desktops instead of assuming every browser can run the same local model or graphics workload.',
'b':'Local processing can improve privacy when data genuinely stays on the device, but “browser AI” does not automatically mean “no cloud.” A page may still download model files, send analytics or call remote APIs for another part of the workflow. Privacy wording should describe the actual data path rather than the marketing label.',
'c':'WebGPU can accelerate parallel workloads, while WebAssembly can provide portable near-native execution for suitable code. Real performance depends on model size, memory bandwidth, browser implementation and thermal limits, so one benchmark should not be treated as a guarantee for every device.',
'd':'Progressive loading helps large local tools feel usable. Show download size, loading state and a clear fallback before committing a user to hundreds of megabytes. Cache responsibly and offer a way to clear stored models or data when storage becomes significant.',
'e':'For developers, the practical question is whether local execution improves the task enough to justify complexity. Measure startup time, memory, battery and output quality alongside raw speed before moving an existing server workflow into the browser.'},
'tech/chrome-151-august-2026-security-update.html':{
'a':'For any Chrome security article, first verify the browser version that is actually installed. Open Chrome’s version/update page, allow the update check to complete and restart when required. Managed work or school devices may receive updates on an administrator-controlled schedule, so policy can affect timing.',
'b':'A vulnerability listed in a security bulletin does not automatically mean every user was attacked. Severity describes potential impact under certain conditions, while active exploitation is a separate claim that should only be made when the vendor or another reliable source states it.',
'c':'Keep the official Chrome release or security note linked with the article. Version numbers can differ by platform and rollout stage, and an article written during rollout can become misleading if the date is removed later. Dated source context lets a reader understand which build the advice refers to.',
'd':'After updating, keep extensions and the operating system current as well. A patched browser can still be exposed through a malicious extension, compromised device or phishing page. Security updates reduce known software risk; they do not replace ordinary account and browsing hygiene.',
'e':'If an update causes a reproducible problem, collect the exact version, error and extension list before changing multiple settings. Avoid downloading unofficial browser binaries as a workaround for a temporary rollout issue.'},
'tech/firefox-154-security-update-2026.html':{
'a':'Confirm the installed Firefox version before interpreting a security advisory. Firefox, Firefox ESR and platform-specific packages can have different version tracks, so the fix status for one channel should not be assumed for another. Use the browser’s About page or the package manager used by the device.',
'b':'Security ratings describe the potential impact of a flaw, not proof that a particular computer was compromised. If an article discusses exploitation, that statement should come from Mozilla or another authoritative incident source rather than being inferred from a “high” severity label.',
'c':'After a browser update, restart fully so the new executable is running. Users who leave browsers open for many days can download an update without actually switching to the patched process until restart. Managed environments may need administrator deployment instead.',
'd':'Extensions, downloaded files and phishing remain separate risks. Keep add-ons minimal, remove extensions that are no longer needed and review permission changes. A fully patched browser cannot make a fraudulent login page trustworthy.',
'e':'For troubleshooting, save the version and a clean reproduction before rolling back. An old build may restore compatibility but also reintroduce known security issues, so rollback should be a temporary diagnostic step rather than a default long-term fix.'},
'tech/passkeys-2026.html':{
'a':'A passkey replaces the shared password secret with public-key authentication tied to a device or credential provider. The private key is not sent to the website during sign-in, which helps against ordinary phishing pages that try to steal reusable passwords.',
'b':'Before removing old sign-in methods, understand account recovery. Check whether the service lets you add more than one passkey, synchronize through a trusted platform account, use a hardware security key or keep another recovery path. Losing every enrolled device should not become a permanent lockout.',
'c':'Biometrics such as fingerprint or face unlock normally protect access to the credential on the device; the website receives an authentication result rather than the raw biometric scan. The exact device behavior still depends on the operating system and credential provider, so use screen lock and device encryption properly.',
'd':'Passkeys reduce some phishing risk but do not solve every account-security problem. Session theft, malicious apps, social engineering of support staff and weak recovery channels can still matter. Keep important devices updated and review active sessions after suspicious activity.',
'e':'Adopt passkeys gradually on high-value accounts and test recovery while you still have access. The goal is a stronger and easier sign-in system, not deleting every password before the services you use have reliable passkey support.'},
'tech/post-quantum-encryption-explained.html':{
'a':'Post-quantum migration is mainly a cryptography and infrastructure planning problem, not a reason for ordinary users to replace devices immediately. Organizations first need to inventory where vulnerable public-key algorithms are used in TLS, VPNs, certificates, software signing and long-lived encrypted data.',
'b':'Hybrid approaches combine established algorithms with post-quantum methods during transition so compatibility and new protection can be tested together. The details depend on the protocol and implementation, which is why vendors and standards bodies publish migration guidance rather than telling every site to invent its own scheme.',
'c':'Long-lived sensitive data deserves special attention because an attacker could collect encrypted traffic now and attempt to decrypt it later if future capabilities improve. That risk is different from claiming a cryptographically relevant quantum computer already exists today.',
'd':'Developers should keep cryptographic libraries and platforms updated, avoid hard-coding obsolete algorithms and follow standards implemented by reputable libraries. Rolling a custom post-quantum protocol without expert review can create new vulnerabilities even if the underlying mathematical primitive is strong.',
'e':'For users, normal security maintenance still matters most: current browsers, operating systems and trusted services. Much of the migration should happen underneath applications as vendors adopt standardized algorithms.'},
'tech/qr-code-phishing-quishing.html':{
'a':'A QR code hides the destination until it is scanned, which removes the visual link preview people often use to judge an ordinary hyperlink. The safest habit is to use a scanner that shows the decoded text or URL before opening it and to read the domain carefully.',
'b':'Be especially cautious when a QR code asks for login, payment, account recovery or app installation. A sticker placed over a legitimate restaurant, parking or payment QR can redirect a user even though the physical location looks trustworthy. Check printed branding and the final domain rather than relying on the surroundings alone.',
'c':'Shortened URLs make inspection harder. If a code resolves through a redirect, pause before entering credentials and confirm the final site independently. For banking or government services, opening the official app or typing a known address can be safer than following an unexpected QR path.',
'd':'Scanning an image is not the same as granting every permission. A standard QR usually contains data such as a URL or text; the danger often begins when the user opens the destination, downloads something or provides information. Keep the phone updated and do not approve unusual permission requests merely because they followed a scan.',
'e':'If you already entered a password on a suspicious destination, change the credential from the real service, review sessions and enable stronger sign-in protection. For a payment, contact the provider using an official channel rather than replying to the suspicious page.'},
'tech/toxicpanda-android-malware-2026.html':{
'a':'Android malware that abuses Accessibility, VPN or debugging capabilities is dangerous because those permissions can affect far more than one app screen. Treat any unexpected request for Accessibility control, device-admin style power, VPN creation or wireless debugging as a reason to stop and verify the app’s purpose.',
'b':'Install apps from trusted sources and keep Play Protect or the equivalent device security features enabled. Sideloading can be legitimate for developers, but a random message that asks a normal user to install an APK and then enable powerful permissions should be treated as high risk.',
'c':'Accessibility access is designed for legitimate assistive functionality, yet it can also allow an abusive app to observe interface content or perform actions. Review the list of enabled accessibility services periodically and remove access from apps that no longer need it.',
'd':'VPN permission is not automatically suspicious—many legitimate privacy and enterprise apps use it—but users should understand which app is routing traffic and why. Wireless ADB is primarily a developer feature and should not be left enabled casually on an everyday phone.',
'e':'If compromise is suspected, disconnect from sensitive accounts, remove unknown administrative or accessibility permissions, update the device and follow guidance from the device vendor or a trusted security professional. Changing a banking password on a still-compromised phone may not be enough.'}
}

def render(title,item):
    esc=html.escape
    return '\n'.join([
        START,
        '<section class="section" data-article-value-guide><div class="container article"><details class="nn-compact-detail"><summary><strong>Practical use, verification and limitations</strong></summary>',
        f'<p>{esc(item["a"])}</p>',f'<p>{esc(item["b"])}</p>',f'<p>{esc(item["c"])}</p>',f'<p>{esc(item["d"])}</p>',f'<p>{esc(item["e"])}</p>',
        f'<p><strong>Reader check:</strong> For {esc(title)}, keep the original source, relevant version or input values available while applying the advice. If a decision is financial, medical, legal, security-critical or otherwise high impact, confirm the final action with the appropriate authoritative source rather than relying on one web article alone.</p>',
        '</details></div></section>',END,''])

def get_title(text,path):
    m=re.search(r'<h1\b[^>]*>(.*?)</h1>',text,re.I|re.S)
    if not m: return path.stem.replace('-',' ').title()
    s=re.sub(r'<[^>]+>',' ',m.group(1)); s=re.sub(r'\s+',' ',s).strip()
    return html.unescape(s)

def apply(path,item):
    text=path.read_text(encoding='utf-8')
    block=render(get_title(text,path),item)
    if START in text:
        text=re.sub(re.escape(START)+r'.*?'+re.escape(END)+r'\n?',block,text,count=1,flags=re.S)
    else:
        pos=text.lower().rfind('</main>')
        if pos<0: raise RuntimeError('Missing </main>: '+str(path))
        text=text[:pos]+block+text[pos:]
    path.write_text(text,encoding='utf-8')

def main():
    changed=[]
    for rel,item in DATA.items():
        path=ROOT/rel
        if not path.exists(): raise SystemExit('Missing '+rel)
        apply(path,item); changed.append(rel); print('Deepened article/guide:',rel)
    (ROOT/'article-value-changed-files.txt').write_text('\n'.join(changed)+'\n',encoding='utf-8')
    print('Changed article/guide pages:',len(changed))

if __name__=='__main__': main()
