#!/usr/bin/env python3
from pathlib import Path
import re

ROOT=Path(__file__).resolve().parents[2]
START='<!-- NEXUSNOVA_LIVE_VALUE_START -->'
END='<!-- NEXUSNOVA_LIVE_VALUE_END -->'
BLOCKS={
'aqi-live.html': '''<section class="section" data-live-value-guide><div class="container article"><details class="nn-compact-detail"><summary><strong>How to read this AQI page</strong></summary><p>The AQI number on this page is an estimate derived from the PM2.5 observation available to NexusNova, so read the pollutant concentration, observation timing and method together rather than treating the headline index as a stand-alone medical measurement. A city can disappear when the underlying station or feed has no usable recent observation; that is safer than carrying an old number forward as if it were current.</p><p>For practical use, compare nearby observations when available and look for a pattern rather than reacting to a tiny change in one reading. Weather, local traffic, dust, smoke and station placement can make neighboring locations differ. If air quality affects health, outdoor work, school or travel, use the relevant government or public-health guidance for your location and follow medical advice for individual conditions.</p><p>NexusNova does not use this page to diagnose exposure or predict a person’s symptoms. The value is a transparent reference layer: source context, calculation method and limitations should remain visible so a user can decide whether a more authoritative local source is needed.</p></details></div></section>''',
'crypto-live.html': '''<section class="section" data-live-value-guide><div class="container article"><details class="nn-compact-detail"><summary><strong>How to read the crypto references</strong></summary><p>Crypto prices can move between one refresh and the next, so the displayed BTC, ETH, BNB, SOL or XRP value should be read with its source and freshness information. The PKR reference is a derived conversion when the page combines a crypto quote with a currency reference; it is not a guaranteed executable price from a Pakistani exchange, bank or dealer.</p><p>Before using a number for a purchase, transfer or portfolio decision, compare the exact trading pair, exchange, spread, fee and timestamp that apply to the transaction you may actually make. Two legitimate services can show different values at the same moment because liquidity, pair construction and update timing differ.</p><p>This page is designed for market reference and comparison, not for investment advice, price prediction or trade execution. If the source fails, NexusNova should leave the value unavailable rather than inventing a replacement. A user who needs an auditable transaction value should use the receipt or order history from the platform where the transaction occurred.</p></details></div></section>''',
'currency-rates.html': '''<section class="section" data-live-value-guide><div class="container article"><details class="nn-compact-detail"><summary><strong>How to use a currency reference correctly</strong></summary><p>The converter is most useful for planning and comparison when you keep the reference date and currency pair visible. A daily or reference-market rate is different from the cash, card, remittance or bank rate a person may actually receive because providers can add spreads, commissions, taxes or service charges.</p><p>For a real payment, first note the amount and direction of conversion, then compare the NexusNova reference with the quote from the bank, exchange company or payment provider you intend to use. If you reverse the pair, remember that simple reciprocal math does not reproduce a provider’s buy-and-sell spread.</p><p>NexusNova should not label a stale or missing rate as current. The page therefore treats source timing and availability as part of the answer, not as decoration. For accounting, contracts, tax filings or regulated reporting, use the exchange-rate source required by the relevant authority or document instead of assuming a general web reference is acceptable.</p></details></div></section>''',
'earthquakes-live.html': '''<section class="section" data-live-value-guide><div class="container article"><details class="nn-compact-detail"><summary><strong>How to interpret a recent earthquake feed</strong></summary><p>Earthquake feeds are event reports, not a forecast. An event can be revised after the first publication as more seismic data is processed, so magnitude, depth, coordinates or status may change. Read the event time and source link before comparing two entries that appear similar.</p><p>The Pakistan-region list is a geographic filter over the available feed, not a statement that every event was felt in Pakistan or caused damage. Felt intensity depends on distance, depth, local ground conditions and building response, which cannot be inferred from magnitude alone. For safety decisions, aftershocks or emergency instructions, follow the relevant seismic and disaster-management authorities.</p><p>If the feed is unavailable, NexusNova should not create synthetic earthquakes or retain an old event as if it were new. This page is best used to discover recent reported events and then open the authoritative source for the event detail when the information matters.</p></details></div></section>''',
'pulse.html': '''<section class="section" data-live-value-guide><div class="container article"><details class="nn-compact-detail"><summary><strong>How to read a Pulse snapshot</strong></summary><p>Pulse combines several already-published NexusNova references on one compact screen, but those cards do not share one universal clock. Currency, fuel, weather, gold and earthquake data can each have a different update schedule, so the timestamp or reference period on the underlying page matters more than the fact that the cards appear together.</p><p>Use Pulse to notice which signal deserves a closer look, then open the detailed source page before making an important decision. A fuel reference may be an officially published period, while a weather card can be a model forecast and a gold card can be an international-derived PKR reference. Treating all three as the same type of “live” data would be misleading.</p><p>Pulse does not invent missing values or causal explanations. If one source fails, that card should remain unavailable while the others continue to show their own verified context. This separation is intentional so a compact dashboard does not turn uncertainty into a confident-looking number.</p></details></div></section>''',
'sports-live.html': '''<section class="section" data-live-value-guide><div class="container article"><details class="nn-compact-detail"><summary><strong>How to read a live sports feed</strong></summary><p>A sports feed can lag the television broadcast or stadium clock because score providers receive, normalize and publish updates on their own cadence. “Live” on this page means the latest event state available from the configured source, not a guarantee of second-by-second synchronization with every competition.</p><p>When a score matters, check the competition name, teams, start time and status together. Similar team names, abandoned matches, rain delays, extra time or feed corrections can make a single number easy to misread. Pakistan-first sorting changes presentation only; it does not change the source result or create a score when none is supplied.</p><p>NexusNova uses the feed as an informational reference and should leave an event unavailable rather than inventing a fixture or result. For betting, official records, ticketing, disciplinary decisions or any other high-impact use, rely on the competition organizer or the official scoreboard instead of this convenience page.</p></details></div></section>'''
}

def apply(path, block):
    text=path.read_text(encoding='utf-8')
    wrapped=START+'\n'+block+'\n'+END+'\n'
    if START in text:
        text=re.sub(re.escape(START)+r'.*?'+re.escape(END)+r'\n?',wrapped,text,count=1,flags=re.S)
    else:
        pos=text.lower().rfind('</main>')
        if pos<0: raise RuntimeError('Missing </main>: '+path.name)
        text=text[:pos]+wrapped+text[pos:]
    path.write_text(text,encoding='utf-8')

def main():
    changed=[]
    for name,block in BLOCKS.items():
        path=ROOT/name
        if not path.exists(): raise SystemExit('Missing '+name)
        apply(path,block); changed.append(name); print('Deepened LIVE page:',name)
    (ROOT/'live-value-changed-files.txt').write_text('\n'.join(changed)+'\n',encoding='utf-8')

if __name__=='__main__': main()
