#!/usr/bin/env python3
from __future__ import annotations

from pathlib import Path
import html
import re

ROOT = Path(__file__).resolve().parents[2]
START = '<!-- NEXUSNOVA_COMPACT_TOOL_GUIDE_START -->'
END = '<!-- NEXUSNOVA_COMPACT_TOOL_GUIDE_END -->'
CHANGED = ROOT / 'tool-depth-remediation-changed-files.txt'

FAMILY_STEPS = {'calculator': ['Read the labels and confirm every number is in the unit or format expected by {name} before calculating.',
                'Enter the source values in {name}, run the calculation, and keep the original inputs visible while you review the result.',
                'Check the result from {name} against the real question you are answering, including the correct base value, period, unit and rounding rule.'],
 'developer': ['Enter the source value exactly as it appears in your code, page or configuration before asking {name} to generate or convert anything.',
               'Copy the output from {name} into a test or staging context first, then inspect syntax, URLs and formatting before production use.',
               'Validate the final result from {name} with the destination platform or specification because generated helper output does not replace platform rules.'],
 'document': ['Prepare the names, amounts and line items you want to include before entering them into {name} so the final document can be checked efficiently.',
              'Build the document in {name}, review totals and labels, then generate or print a test copy before sending it to another person.',
              'Open the exported result from {name} and compare it with the source agreement, quote or records so missing details are caught before delivery.'],
 'gaming': ['Record your current game and hardware settings before using {name} so you always have a baseline to return to.',
            'Enter the values requested by {name}, calculate or convert them, and test the result in a controlled practice session rather than changing several settings at once.',
            'Compare the output from {name} with feel, game-specific behavior and saved baseline values before deciding that the new setting is better.'],
 'image': ['Keep the original image, then load a working copy into {name} and choose only the settings needed for the destination.',
           'Process the file with {name} and inspect the output at normal viewing size, paying attention to text, transparency, gradients and sharp edges.',
           'Compare the exported file from {name} with the original for dimensions, file size, metadata and visible quality before replacing any master copy.'],
 'media': ['Enter the exact public video URL or identifier in {name} and confirm the loaded media belongs to the intended source.',
           'Use {name} to view or save the available asset, then check its dimensions and quality before placing it in another document or page.',
           'Respect the rights attached to content accessed through {name}; technical availability does not automatically grant permission to republish another creator’s material.'],
 'network': ['Enter the exact hostname, domain, address or URL expected by {name}; a typo can make a healthy service look broken.',
             'Run {name} and record the returned value together with the time of the check so later changes can be compared properly.',
             'Confirm any important finding from {name} with the authoritative DNS, hosting, certificate or network source before changing production configuration.'],
 'ocr': ['Choose the clearest source image you have, crop distracting background where practical, and load the image into {name}.',
         'Run {name}, then compare the extracted text line by line with the source image rather than copying it immediately.',
         'Correct names, dates, amounts and similar high-impact fields from {name} manually before using the text in another document or system.'],
 'pdf': ['Keep the original PDF or source files, then add only the documents or pages needed for the job in {name}.',
         'Use {name} to create the new PDF and immediately reopen the result to check order, page count, orientation and readability.',
         'Retain the source files until the output from {name} has been checked for forms, links, signatures or other document features that matter.'],
 'qr': ['Load or enter the exact content in {name}, then inspect the decoded or generated value before treating the QR image as final.',
        'Test the result from {name} on another device when the code will be printed, published or used for a payment or login destination.',
        'Check the destination domain and privacy implications separately because {name} can encode or decode content without certifying that content as trustworthy.'],
 'random': ['Define the eligible range or list before running {name} and remove accidental duplicates unless extra weight is intentional.',
            'Generate one result with {name} under the rules agreed before the draw, rather than editing the candidate set after seeing the outcome.',
            'Record the input set and result from {name} when an informal draw needs to be explained, and use an audited system when regulation requires it.'],
 'reference': ['Select the relevant location, date or reference option in {name} and note the source date shown by the page when available.',
               'Use {name} for planning, then compare important dates, times or directions with the official or locally trusted source that applies to you.',
               'Recheck {name} close to the event when official announcements, local conventions or time-sensitive data can change the practical answer.'],
 'security': ['Use {name} on a trusted device and avoid exposing real high-value credentials to any page unless you understand how the input is handled.',
              'Apply the result from {name} as one security layer, then add unique credentials, multi-factor authentication or passkeys where the account supports them.',
              'Review the broader account-recovery and phishing risk after using {name}; a strong local result cannot protect a compromised device or deceptive login page.'],
 'storage': ['Use {name} for information that is appropriate for ordinary browser storage and keep sensitive secrets in a dedicated secure system.',
             'Enter or update the information in {name}, then refresh or reopen the page once if persistence is important to your workflow.',
             'Copy anything important out of {name} into your normal backup or record system instead of treating a browser note as the only copy.'],
 'test': ['Use the same device and similar conditions each time you run {name} so repeated scores are more comparable.',
          'Complete several attempts in {name} and compare a typical or average result instead of treating one extreme score as definitive.',
          'Interpret the score from {name} as a browser-assisted practice metric, not a medical, employment or laboratory certification unless an organization explicitly says otherwise.'],
 'text': ['Paste or enter only the text needed for the task, then review the available options in {name} before transforming anything.',
          'Run {name} on a copy of the text so names, acronyms, wording or formatting can be compared with the original afterward.',
          'Read the final output from {name} once before publishing or submitting it, especially when capitalization, spelling or document wording matters.'],
 'time': ['Confirm whether the source uses UTC, a named time zone, seconds or milliseconds before entering the value in {name}.',
          'Run the conversion or comparison in {name} and keep both the original instant and the displayed local interpretation visible while checking it.',
          'For future events, recheck the result from {name} when daylight-saving or government time-zone rules could change the displayed clock time.'],
 'timer': ['Choose the interval and alert conditions in {name}, then check device volume and power settings before starting an important session.',
           'Start {name} with the browser tab available and keep the device awake when an exact alert matters to the task.',
           'At the end of {name}, record the outcome or reset deliberately rather than relying on the timer itself to remember what was completed.']}

CONTENT = {'age-calculator.html': {'caution': 'Check the birth date and reference date before relying on the result, especially for admissions, eligibility or official forms. Calendar age can be interpreted differently by an organization that counts boundary dates in a special way, so the organization’s rule remains authoritative.',
                         'example': 'If a person was born on 15 June 2000 and the reference date is 10 September 2026, the result should reflect completed years first and then the remaining months and days. This is more precise than treating every year or month as the same length.',
                         'family': 'calculator',
                         'purpose': 'Use the Age Calculator to work out calendar age from a date of birth to a chosen reference date. It is useful when you need years, months and days rather than a rough estimate based on total days divided by 365.'},
 'ai-prompt-builder.html': {'caution': 'A better prompt can reduce ambiguity, but it cannot guarantee factual accuracy or safe output from another AI system. Do not paste passwords, private keys, confidential documents or personal data into an external AI service unless you understand that provider’s data policy.',
                            'example': 'For a product-description task, you can state the product, audience, tone, facts that must be included and the exact output format. The resulting prompt gives the destination AI a clearer brief than a one-line request such as “write something good about this product.”',
                            'family': 'text',
                            'purpose': 'The AI Prompt Builder helps turn a loose request into a clearer prompt by separating the goal, context, constraints and preferred output. It is most useful when an AI answer keeps missing details because the original instruction is vague or incomplete.'},
 'ai-token-calculator.html': {'caution': 'Always check the tokenizer or usage dashboard for the exact model when cost or context limits matter. Model providers can use different tokenizers and pricing rules, so an estimate from this tool should not be treated as an invoice or guaranteed request size.',
                              'example': 'A long article may contain a few thousand words but a different number of tokens because punctuation, numbers and word fragments can be split differently. Use the estimate to compare prompt versions or decide whether a document is likely to fit within a model’s context allowance.',
                              'family': 'calculator',
                              'purpose': 'The AI Token Calculator gives an approximate token count for text so you can plan prompt size, context windows and rough usage before sending content to an AI model. Tokenization is model-dependent, so this page is a planning aid rather than an exact billing meter.'},
 'ai-vram-calculator.html': {'caution': 'Treat the result as an estimate, not a promise that a model will run on a particular GPU. KV cache, batch size, context length, framework overhead, offloading and quantization implementation can change real VRAM use, so check the model and runtime documentation before purchasing hardware.',
                             'example': 'A 7-billion-parameter model stored at 16-bit precision needs roughly 14 GB just for raw parameter storage before runtime overhead, cache and application memory are considered. Lower-bit quantization can reduce parameter memory, but actual runtime use still depends on the software and workload.',
                             'family': 'calculator',
                             'purpose': 'The AI VRAM Calculator estimates memory requirements for loading or running a model from inputs such as parameter count, numeric precision and overhead assumptions. It helps compare configurations before downloading a large model or choosing a GPU.'},
 'avif-to-jpg.html': {'caution': 'JPEG is lossy and cannot preserve transparency, so transparent AVIF areas must be flattened to an opaque background. Keep the AVIF original as the master file and verify metadata separately if capture date, location or other embedded information matters.',
                      'example': 'If a website rejects an AVIF photo, convert a copy to JPG and then open the JPG at normal viewing size before uploading it. Compare faces, gradients and text edges so you can confirm the compatibility gain is worth any compression loss.',
                      'family': 'image',
                      'purpose': 'The AVIF to JPG Converter creates a broadly compatible JPEG copy of an AVIF image for apps, forms or editors that do not accept AVIF. The conversion changes the image encoding; it does not add detail that was missing from the source.'},
 'bill-split-tip-calculator.html': {'caution': 'Check whether tax, service charge or delivery fees are already included before adding another percentage. Real groups may not split equally when people ordered different items, so use the calculator only for the sharing rule you actually agreed on.',
                                    'example': 'For a 10,000 bill split between four people with a 10% tip, the tip is 1,000 and the total becomes 11,000. An equal split gives 2,750 per person, assuming everyone shares the bill and tip equally.',
                                    'family': 'calculator',
                                    'purpose': 'The Bill Split & Tip Calculator divides a bill across a chosen number of people and can add a tip percentage to the shared total. It is useful for quickly comparing the base share, tip amount and per-person payment without doing several calculations manually.'},
 'bmi-calculator.html': {'caution': 'BMI needs different interpretation for children, pregnancy, some athletic body types and many individual health situations. Do not use a browser BMI number to diagnose a condition or choose treatment; discuss important health decisions with a qualified healthcare professional.',
                         'example': 'At 70 kg and 1.75 m, BMI is about 22.9 because 70 is divided by 1.75 squared. If you use imperial measurements, make sure the tool is set to the correct unit system before comparing the result with any reference range.',
                         'family': 'calculator',
                         'purpose': 'The BMI Calculator converts height and weight into body mass index using the standard BMI formula. It can provide broad screening context, but it does not directly measure body fat, fitness, muscle mass or an individual diagnosis.'},
 'calculator.html': {'caution': 'Digital calculators can show floating-point rounding effects with long decimal operations. For tax filings, engineering tolerances, legal totals or any calculation governed by a required rounding method, confirm the rule and verify the final number with the authoritative source.',
                     'example': 'If four items cost 18 each and you subtract a fixed discount of 6, calculate 18 × 4 first to get 72 and then subtract 6 to get 66. Breaking a task into steps makes it easier to spot a wrong operator or copied number.',
                     'family': 'calculator',
                     'purpose': 'The Basic Calculator handles everyday arithmetic such as addition, subtraction, multiplication and division. It is intended for quick numerical work where you want a visible result without opening a spreadsheet or a more advanced scientific calculator.'},
 'date-difference-calculator.html': {'caution': 'Confirm whether your real task uses elapsed time or inclusive date counting before relying on the output. Deadlines, visas, contracts and payroll rules can define counting conventions explicitly, and those official rules take priority over a general calculator.',
                                     'example': 'From 1 September to 10 September the elapsed gap is nine days when the starting instant is not counted twice. Some booking, legal or attendance rules count both boundary dates, which can make the practical answer different by one day.',
                                     'family': 'calculator',
                                     'purpose': 'The Date Difference Calculator measures the calendar gap between two selected dates. It is useful for elapsed-day questions, project intervals and planning where simply subtracting month numbers would be misleading.'},
 'discount-calculator.html': {'caution': 'Sequential discounts should be calculated one after another rather than simply added together. A retailer can also apply tax or fees after the discount, so compare the calculator result with the actual checkout total when making a purchase decision.',
                              'example': 'A 20% discount on 5,000 saves 1,000 and leaves 4,000 before any later tax, delivery fee or service charge. If another 10% discount is then applied to 4,000, the final price is 3,600 rather than 3,500.',
                              'family': 'calculator',
                              'purpose': 'The Discount Calculator works out the amount saved and the reduced price from an original price and discount percentage. It is useful for checking sale labels, comparing offers or understanding how much a percentage reduction changes the base price.'},
 'dns-lookup.html': {'caution': 'DNS results can vary by resolver, record type, geography and propagation timing. A successful lookup does not prove that the destination service is healthy or secure, so verify web, mail or other services separately when troubleshooting.',
                     'example': 'After changing a domain’s DNS, look up the domain and compare the returned record with the value configured at your DNS provider. If different resolvers still show old data, cache and TTL timing may explain the delay rather than a broken website.',
                     'family': 'network',
                     'purpose': 'DNS Lookup helps inspect the records returned for a domain, such as address or name-server information supported by the page. It is useful when checking where a domain resolves or when diagnosing a configuration change.'},
 'edpi-calculator.html': {'caution': 'eDPI does not include field of view, acceleration, raw-input behavior, Windows pointer settings, polling rate or physical desk space. Keep your old values before changing settings and compare within a consistent game context rather than treating one number as a universal sensitivity standard.',
                          'example': 'At 800 DPI and 0.50 in-game sensitivity, eDPI is 400. A different pair can produce the same eDPI, but that does not automatically make settings equivalent across different games with different rotation scales or input behavior.',
                          'family': 'gaming',
                          'purpose': 'The Gaming eDPI Calculator combines mouse DPI and in-game sensitivity into one comparison value. It is useful for documenting a setup or comparing sensitivity values inside the same game or a directly comparable sensitivity scale.'},
 'emi-calculator.html': {'caution': 'Real loans can include processing fees, insurance, taxes, variable rates, early-payment rules or a different compounding convention. Use the lender’s official repayment schedule and contract as the final source before signing or budgeting around a financing decision.',
                         'example': 'For the same loan amount, extending the term usually lowers the monthly payment but can increase total interest paid over the life of the loan. Run two terms side by side to see the monthly trade-off before discussing an offer with a lender.',
                         'family': 'calculator',
                         'purpose': 'The EMI Calculator estimates a regular loan payment from principal, interest rate and repayment term. It helps compare financing scenarios and understand how changing the rate or term can affect the approximate monthly instalment.'},
 'fps-frame-time-calculator.html': {'caution': 'The calculation describes the mathematical relationship between average FPS and frame time, not the full responsiveness of a game. Display refresh, input latency, frame pacing, CPU/GPU stalls and synchronization settings can affect the actual experience.',
                                    'example': 'At 60 FPS, one frame is about 16.67 ms; at 120 FPS it is about 8.33 ms. A lower average frame time can feel smoother, but consistent delivery matters too because large spikes can still cause visible stutter.',
                                    'family': 'gaming',
                                    'purpose': 'The FPS & Frame Time Calculator converts frames per second into approximate time per frame and back again. This makes it easier to compare performance targets using both FPS and milliseconds, which describe the same rendering cadence from different angles.'},
 'gamer-name-generator.html': {'caution': 'A generated result may already belong to someone else or be restricted by a platform’s naming rules. Avoid impersonation, abusive terms and protected brand names, and confirm availability directly on the service where you want to register the username.',
                               'example': 'Generate several candidates, shortlist the ones that are easy to read and say, then search the exact spelling on the game or platform you plan to use. A small spelling change can make a name distinct without copying an existing player or brand.',
                               'family': 'text',
                               'purpose': 'The Gamer Name Generator creates username ideas from naming patterns so you can explore options faster than brainstorming from scratch. It is intended for inspiration rather than for checking account availability, ownership or trademark status.'},
 'gaming-sensitivity-converter.html': {'caution': 'Cross-game sensitivity conversion cannot make two engines completely identical. Mouse DPI, raw-input settings, acceleration, zoom multipliers, field of view and personal preference can all affect the final feel, so save the original settings before experimenting.',
                                       'example': 'Enter the sensitivity you actually use in CS2, convert it, then test the Valorant result in a practice range before changing muscle-memory habits around it. Small adjustments may still feel better because field of view and game mechanics differ.',
                                       'family': 'gaming',
                                       'purpose': 'The CS2 Sensitivity Converter to Valorant converts a sensitivity value using the relationship built into this page so you can start from a familiar aiming feel when moving between the two games. It provides a baseline, not a guarantee of identical physical perception.'},
 'gaming-settings-notes.html': {'caution': 'Do not store account passwords, recovery codes or private keys in a general settings note. Hardware, patches and game updates can also change how a saved setting feels, so treat old notes as historical context rather than a permanent recommendation.',
                                'example': 'Record the game, mouse DPI, in-game sensitivity, resolution or field of view when relevant, and the date you changed the setup. If performance improves or worsens later, you can compare against a known baseline instead of guessing what changed.',
                                'family': 'storage',
                                'purpose': 'Gaming Settings Notes gives you a simple place to record settings such as game name, DPI, sensitivity or other values you want to remember. A useful note makes later comparisons reproducible instead of relying on memory.'},
 'heic-to-jpg.html': {'caution': 'JPEG uses lossy compression and may not preserve metadata, depth information or other HEIC-specific data. Important photos should keep their HEIC master, and metadata should be checked separately when capture date or location is important.',
                      'example': 'Keep the HEIC original, convert a copy to JPG, and open the result in the exact form or editor where you plan to use it. This confirms both compatibility and visual quality before you delete or archive anything.',
                      'family': 'image',
                      'purpose': 'The HEIC to JPG Converter makes a JPEG copy of an HEIC photo for services or software that do not accept HEIC. JPG is widely compatible, while HEIC can preserve more efficient storage and additional image information depending on the source.'},
 'image-compressor.html': {'caution': 'Keep the original image before creating a smaller copy because repeated lossy saves can compound quality loss. Check transparency, metadata and fine detail after export, and never assume that a smaller file preserves every property of the source.',
                           'example': 'A large web photo can often be resized to the display dimensions first and then compressed while you compare faces, gradients and text at normal viewing size. The best setting is the smallest file that still looks acceptable for the intended use.',
                           'family': 'image',
                           'purpose': 'Image Compressor & Resizer reduces image file size and can adjust dimensions for easier uploads, faster pages or smaller attachments. Compression and resizing are different operations, so choose each control based on the final use rather than chasing the smallest file at any cost.'},
 'image-metadata-remover.html': {'caution': 'Removing metadata cannot hide details that are visibly present in the pixels, such as a face, address sign, document name or reflected screen. It also does not remove copies already uploaded elsewhere, so privacy review must include both metadata and visible content.',
                                 'example': 'After cleaning a photo, inspect the output with a metadata viewer if the information is sensitive, then open the image normally to make sure the visible picture is still correct. Keep the original privately if you may need the original capture information later.',
                                 'family': 'image',
                                 'purpose': 'Image Metadata Remover is designed to create a copy with supported embedded metadata removed before sharing. This can reduce accidental exposure of information such as camera details or location fields when those fields exist in the source.'},
 'image-resizer.html': {'caution': 'Upscaling creates more pixels but cannot recreate detail that was never captured. Disabling aspect-ratio locking can stretch faces or objects, and repeated resizing from already compressed copies can reduce quality, so keep the highest-quality original.',
                        'example': 'If a 4000 × 3000 photo only needs to appear around 1200 pixels wide on a page, resize a copy while keeping the aspect ratio linked. Check small text and edges after export rather than assuming more pixels always mean a better result.',
                        'family': 'image',
                        'purpose': 'The Image Resizer changes pixel dimensions so an image better fits a website, document, profile image or upload limit. It is most useful when the target width, height or aspect ratio is known before export.'},
 'image-to-text-ocr.html': {'caution': 'OCR can confuse similar characters, punctuation, tables, handwriting and low-resolution text. Treat the output as a draft that needs human review, especially for legal, financial, medical or identity-related information where one incorrect character could matter.',
                            'example': 'For a photographed document, crop unnecessary background, make sure the page is not heavily tilted, then run OCR and compare names, dates and numbers with the image before copying the text into another document.',
                            'family': 'ocr',
                            'purpose': 'Image to Text OCR extracts readable English text from a screenshot, scan or photograph so you can copy and edit it instead of retyping everything manually. OCR works best when letters are sharp, upright and clearly separated from the background.'},
 'invoice-maker.html': {'caution': 'Invoice numbering, tax registration, currency wording and required seller or buyer details vary by country and business type. Keep your own records and follow the rules that apply to your business; a browser invoice layout is not a substitute for accounting or tax advice.',
                        'example': 'Add each product or service as a separate line, confirm quantity and unit price, then review subtotal, discount, tax and final total before printing or saving the invoice as PDF. Compare the final document with the agreed quote or order.',
                        'family': 'document',
                        'purpose': 'The Simple Invoice Generator helps assemble customer details, line items, quantities, prices, tax or discount into a printable invoice layout. It is useful for preparing a clear record, but it does not decide the legal or tax requirements for your business.'},
 'ip-cidr-calculator.html': {'caution': 'A valid CIDR range does not prove that every address is usable, assigned or reachable. Routing, reserved addresses, NAT, cloud-provider rules and firewall policy can change real connectivity, so verify the actual network configuration separately.',
                             'example': 'For a /24 network, the calculator can show the network range that shares the first 24 address bits. Use the result to verify whether two IPv4 addresses belong to the same numerical subnet before configuring a device or firewall rule.',
                             'family': 'network',
                             'purpose': 'The IPv4 CIDR & Subnet Calculator works out address-range information from an IPv4 address and prefix length. It is useful for planning networks, checking subnet boundaries and understanding which addresses fall inside a CIDR block.'},
 'jpg-to-pdf.html': {'caution': 'Image-to-PDF conversion does not make a low-resolution image clearer and may not preserve all image metadata. Keep the source images until the PDF has been checked, and use a dedicated document-scanning workflow when searchable text or archival standards are required.',
                     'example': 'Add images in the order you want them to appear, generate the PDF, then reopen the output and check page order, orientation and readability before sending it. A rotated receipt or a missing page is easier to catch before submission.',
                     'family': 'pdf',
                     'purpose': 'JPG to PDF packages one or more JPEG images into a PDF document so they can be shared or printed as pages. It is useful for scans, receipts or photos when the receiving workflow expects a PDF rather than separate image files.'},
 'jpg-to-png.html': {'caution': 'The conversion cannot reconstruct removed JPEG information or create real transparency from an ordinary opaque JPG. Keep the best original available and choose the format based on the next workflow rather than assuming PNG is always higher quality.',
                     'example': 'Use the PNG copy when an editor or upload form specifically requires PNG, then compare file size and visible quality with the JPG. For text-heavy graphics, starting from an original lossless file is better than expecting conversion to recover crisp edges.',
                     'family': 'image',
                     'purpose': 'The JPG to PNG Converter creates a PNG copy for workflows that need PNG or repeated lossless re-saving. Converting format does not restore detail already lost by JPEG compression, so the new PNG may be larger without looking sharper.'},
 'merge-pdf.html': {'caution': 'Forms, bookmarks, links, attachments, encryption and digital signatures can behave differently after PDFs are combined. Keep the original files and inspect any advanced document features separately when they are important.',
                    'example': 'Add the PDFs in the intended sequence, merge them, then open the new file and verify the first page, last page and total page count. If one source has a cover sheet, make sure it appears in the correct place before sharing.',
                    'family': 'pdf',
                    'purpose': 'Merge PDF combines multiple PDF documents into one ordered file. It is useful for submissions, reports or document packs where complete source PDFs need to stay together in a single download.'},
 'meta-tag-generator.html': {'caution': 'Generated metadata cannot guarantee rankings, clicks or a specific search snippet because search engines can rewrite displayed text. Confirm canonical and social URLs, use absolute image URLs where required, and test the published page because social platforms can cache older previews.',
                             'example': 'For an image-resizer page, use a title that names the task and supported formats, then write a description that explains the benefit without repeating keywords unnaturally. Generate the tags and place them in the final page head.',
                             'family': 'developer',
                             'purpose': 'The Meta Tag & Open Graph Generator organizes title, description and social-sharing metadata into copyable HTML. It helps reduce syntax mistakes when preparing a page for search snippets and social link previews.'},
 'minecraft-coordinate-converter.html': {'caution': 'Existing portals, terrain and game-version behavior can affect actual portal linking, so treat converted coordinates as a navigation target rather than a guaranteed spawn block. Check the game edition and current portal mechanics when precise linking matters.',
                                         'example': 'An Overworld X coordinate of 800 and Z coordinate of -400 corresponds to about X 100 and Z -50 in the Nether. The Y value is not scaled by the same 8:1 rule and safe portal placement can still shift the final location.',
                                         'family': 'gaming',
                                         'purpose': 'The Minecraft Nether Coordinate Converter helps translate horizontal Overworld and Nether coordinates using the common 8:1 X/Z relationship. It is useful for planning portal travel and estimating where a linked destination should be built.'},
 'number-to-words.html': {'caution': 'Number wording can vary by region, language and document standard, especially around currency, decimals and the use of “and.” For cheques, contracts or official forms, follow the format required by the institution instead of assuming one written style is universal.',
                          'example': 'Convert 1250 and review the written result before pasting it into a form or invoice. If the destination requires a special currency wording, regional style or legal phrase, edit the text to match that required convention.',
                          'family': 'text',
                          'purpose': 'Number to Words converts a numeric value into written words for easier reading or copying into documents. It is useful for drafts, teaching and basic document preparation where spelling out a number is preferred.'},
 'online-timer.html': {'caution': 'Browsers can be paused or throttled when a device sleeps, enters aggressive battery saving or closes the tab. Do not rely on a web timer alone for medicine, industrial processes, fire safety or any situation where a missed alert could cause harm.',
                       'example': 'Set a 20-minute focus block, start the timer and keep the device awake. When the alert sounds, record what was completed before starting another interval so the timer acts as a clear work boundary.',
                       'family': 'timer',
                       'purpose': 'Online Timer counts down a selected duration for study sessions, presentations, exercise intervals or other routine reminders. It is convenient when a visible browser countdown is enough for the task.'},
 'pakistan-public-holidays-2026.html': {'caution': 'Some holidays depend on official announcements, moon sighting or later government notifications, and private organizations can use different schedules. Recheck important dates close to the event instead of treating an early reference list as permanently fixed.',
                                       'example': 'Use the page to identify a likely holiday before arranging a meeting or travel day, then confirm the date with the relevant government notification, employer, school or bank when the closure affects an important commitment.',
                                       'family': 'reference',
                                       'purpose': 'Pakistan Public Holidays 2026 provides a planning reference for listed public-holiday dates and related notes. It is useful for tentative schedules, but official notifications and organization-specific closures remain the final authority.'},
 'paper-size-converter.html': {'caution': 'Printers, bleed, crop marks and application scaling can change the final output even when the pixel math is correct. Confirm the print shop or device requirements for professional work and do not treat screen DPI assumptions as a universal print standard.',
                               'example': 'An A4 document at 300 DPI needs far more pixels than the same A4 size at 96 DPI because DPI changes the pixel density, not the physical paper dimensions. Use the selected DPI that matches the intended print or export workflow.',
                               'family': 'calculator',
                               'purpose': 'Paper Size & DPI Converter translates physical paper dimensions and pixel requirements for common print or screen-preparation tasks. It is useful when you know a paper size and need to understand the corresponding pixels at a chosen DPI.'},
 'password-generator.html': {'caution': 'Password strength cannot protect against phishing, malware, account-recovery abuse or a compromised device. Never reuse an important password, and do not paste generated credentials into places you do not trust.',
                             'example': 'Generate a long password, save it in a reputable password manager and enable multi-factor authentication or a passkey where available. Avoid shortening or simplifying the result in a way that creates a predictable personal pattern.',
                             'family': 'security',
                             'purpose': 'Strong Password Generator creates unpredictable password candidates so you do not have to invent memorable patterns that attackers can guess. The biggest security benefit comes from using a different generated password for every important account.'},
 'password-strength-checker.html': {'caution': 'A strength score cannot know whether a password has already appeared in a breach unless the tool explicitly performs a breach check, and no score prevents phishing. Avoid entering a real high-value password into any service unless you trust how that service processes the input.',
                                    'example': 'Compare a short dictionary word with a longer unique phrase or generated password and review which factors improve the score. Use the result to identify weak patterns, then store the final credential securely instead of repeatedly testing it in public tools.',
                                    'family': 'security',
                                    'purpose': 'Password Strength Checker evaluates characteristics of a password such as length and character variety to give quick feedback on obvious weaknesses. It is best used as a local screening aid rather than as proof that a credential is safe.'},
 'percentage-calculator.html': {'caution': 'Percent and percentage points are not the same thing, and the selected base value changes the meaning of the result. For tax, finance or reporting, confirm which value is the denominator and which rounding rule the real task requires.',
                                'example': 'To find 15% of 800, multiply 800 by 0.15 to get 120. If you instead want to know what percentage 120 is of 800, divide 120 by 800 and multiply by 100, which also gives 15%.',
                                'family': 'calculator',
                                'purpose': 'Percentage Calculator answers common questions such as finding a percentage of a value or determining what percentage one number represents of another. It is useful when you want the base value and percentage relationship kept explicit.'},
 'percentage-change-calculator.html': {'caution': 'A zero starting value makes ordinary percentage-change formulas undefined, and choosing the wrong baseline can mislead the interpretation. Keep the original and new values visible and use the convention required by the report or organization you are preparing the result for.',
                                       'example': 'If a value rises from 80 to 100, the increase is 20 and the percentage change is 25% because 20 is divided by the original 80. A fall from 100 back to 80 is a 20% decrease, showing why percentage changes are not perfectly symmetric.',
                                       'family': 'calculator',
                                       'purpose': 'Percentage Change Calculator compares an old value with a new value and expresses the difference relative to the starting value. It is useful for price changes, growth, performance comparisons and other before-versus-after measurements.'},
 'photo-cctv-enhancer.html': {'caution': 'Sharpening, contrast and denoising can create artifacts that look like real edges or details. Do not treat an enhanced frame as forensic proof of identity, text or events without professional analysis and access to the original recording.',
                             'example': 'Start from the original frame, make moderate brightness or contrast adjustments, and compare the enhanced copy side by side with the source. Keep the original unchanged so any interpretation can be checked against the unedited image.',
                             'family': 'image',
                             'purpose': 'CCTV Image Enhancer applies browser image adjustments intended to make a dark or low-contrast frame easier to inspect. Enhancement changes visibility and presentation; it cannot recreate reliable detail that the camera never captured.'},
 'png-to-jpg.html': {'caution': 'JPEG cannot preserve transparency and uses lossy compression, so logos, screenshots and line art may look worse after conversion. Keep the PNG original and use JPG only when the destination benefits from that format.',
                     'example': 'Convert a photographic PNG to JPG and inspect the result at normal size, paying special attention to text and sharp edges. If the PNG contains transparent areas, confirm the background color that replaces them in the JPEG.',
                     'family': 'image',
                     'purpose': 'PNG to JPG creates a JPEG copy when smaller photographic files or broader JPEG compatibility are more important than PNG features. The conversion is especially relevant when the destination does not need transparency.'},
 'pomodoro-timer.html': {'caution': 'Browser timers can be affected by sleep mode, background throttling and muted audio. Pomodoro timing is not a medical attention treatment or performance guarantee, so adapt the schedule to your work and use dedicated alarms when missing a time boundary would have serious consequences.',
                         'example': 'Start with a 25-minute work interval and a short break, then note whether that length helps or interrupts the task. Longer deep-work tasks may benefit from adjusted intervals as long as you keep a clear start, stop and break routine.',
                         'family': 'timer',
                         'purpose': 'Pomodoro Timer divides work into focused intervals separated by breaks so you can create a repeatable rhythm without manually watching the clock. The technique is a productivity structure rather than a requirement that every task use the same interval length.'},
 'prayer-times-qibla-pakistan.html': {'caution': 'Prayer-time methods differ in angle settings, juristic conventions and local practice, while phone compasses can be disturbed by metal or poor calibration. For religious observance, follow the authority or timetable you trust when it differs from a general-purpose browser calculation.',
                                     'example': 'Select or allow the relevant location, review the displayed prayer times and compare them with the local mosque or trusted timetable you normally follow. Use the Qibla direction as a directional aid while considering the device’s compass accuracy.',
                                     'family': 'reference',
                                     'purpose': 'Prayer Times & Qibla Direction provides a location-based planning reference for prayer times and the direction toward the Kaaba. It can help with daily orientation, but calculation conventions and local observations can differ.'},
 'private-quick-note.html': {'caution': 'Do not treat a browser note as a password vault, encrypted archive or guaranteed backup. Browser storage can be cleared by privacy settings, cleanup tools or device changes, so sensitive secrets and irreplaceable information belong in purpose-built secure storage.',
                             'example': 'Use it for a short checklist or temporary text you are actively editing, then copy important material into your normal document or backup system when it needs long-term retention. Test whether the note persists after refresh if persistence matters.',
                             'family': 'storage',
                             'purpose': 'Private Quick Note gives you a lightweight browser space for temporary notes without opening a full document editor. It is suited to low-risk reminders, snippets and drafts that you want to keep close while working.'},
 'public-ip-checker.html': {'caution': 'A public IP does not reveal a precise home address and can be shared by many users through carrier-grade NAT or proxies. Do not treat the result as proof of a person’s identity, and use network-provider information when exact routing or ownership matters.',
                            'example': 'Check the address before and after connecting to a VPN to see whether the visible public IP changes. If the same address remains, verify the VPN status and remember that IPv4 and IPv6 can be handled differently.',
                            'family': 'network',
                            'purpose': 'Public IP Checker shows the internet-facing IP address visible to the service used by the page. It is useful when comparing a home connection, VPN session or network change from the perspective of the public internet.'},
 'qr-code-generator.html': {'caution': 'A QR code does not prove that the encoded destination is safe, permanent or owned by you. Avoid embedding secrets in public QR codes, and remember that changing a destination later is impossible for a static QR unless the encoded URL itself redirects.',
                            'example': 'Generate a QR for the final HTTPS page you want people to visit, then scan it with at least two devices before printing. Check the decoded URL character by character if the code will be placed on packaging, posters or permanent material.',
                            'family': 'qr',
                            'purpose': 'QR Code Generator encodes text or a URL into a QR image that compatible scanners can read. It is useful for sharing links, contact text or short information in print and on screens without requiring manual typing.'},
 'qr-code-scanner.html': {'caution': 'Successful decoding does not certify that the destination is trustworthy. The scanner can reveal what the QR contains, but phishing, malicious websites and misleading payment pages must still be evaluated separately.',
                          'example': 'Upload the QR image, read the decoded value and inspect the domain spelling before visiting a link. If the result is a shortened URL or asks for login or payment, treat it with the same caution as an unexpected link in a message.',
                          'family': 'qr',
                          'purpose': 'QR Code Scanner decodes QR content from an uploaded image so you can read the text or inspect a destination before opening it. This is useful when a QR code arrives as a screenshot or image rather than through the camera.'},
 'random-number-generator.html': {'caution': 'Set the rules before seeing the number and do not change the range afterward to fit a preferred outcome. Use an independently audited system for regulated lotteries, gambling, security keys or any process that requires certified randomness.',
                                  'example': 'For a draw among student numbers 1 through 30, set 1 as the minimum and 30 as the maximum before generating. Record the chosen range with the result when other people need to understand the informal draw.',
                                  'family': 'random',
                                  'purpose': 'Random Number Generator selects a number inside the minimum and maximum range you define. It is convenient for games, classroom activities and informal choices where audited or cryptographic randomness is not required.'},
 'random-picker.html': {'caution': 'Remove unintended duplicates and decide the eligibility rules before running the picker. This page is not an audited lottery or cryptographic selection system, so regulated draws should use a method that meets the required legal and audit standard.',
                        'example': 'Enter Ali, Sara, Hina and Omar once each when every person should have equal weight. If a name appears twice, that person effectively receives two chances even if the picker itself selects uniformly.',
                        'family': 'random',
                        'purpose': 'Random Name & Item Picker selects one entry from a list for informal decisions, classroom choices or casual draws. The fairness of the result depends on the list being prepared correctly before the selection.'},
 'reaction-time-test.html': {'caution': 'Display refresh rate, Bluetooth, touch latency, browser workload and human anticipation can affect the measured time. The result is not a medical diagnosis, professional sports certification or laboratory-grade measurement.',
                             'example': 'Run several attempts on the same device and compare the median or average rather than focusing on a single unusually fast result. Repeat later with the same mouse or touchscreen if you want a more meaningful personal baseline.',
                             'family': 'test',
                             'purpose': 'Reaction Time Test estimates the delay between a visual cue and your input as measured through the browser and device. It is best for entertainment and personal comparisons performed under similar conditions.'},
 'rgb-hex-converter.html': {'caution': 'RGB and HEX describe encoded color values, not how every physical screen or printer will reproduce them. For print production or color-critical work, use the color profile and specification required by the destination workflow.',
                            'example': 'RGB 255, 0, 0 converts to #FF0000. After converting a brand color, paste the result into the destination design or CSS and compare visually because color-management and display settings can affect appearance.',
                            'family': 'developer',
                            'purpose': 'RGB ↔ HEX Converter translates common web color values between red-green-blue components and hexadecimal notation. It is useful when design software, CSS or documentation provides the same color in a different representation.'},
 'roman-numeral-converter.html': {'caution': 'Historical inscriptions can use non-standard or extended conventions that differ from the common modern rules. Use the required style guide or historical source when the exact representation matters for academic, legal or publication work.',
                                  'example': 'The ordinary number 49 is written XLIX using standard subtractive notation. When converting an existing Roman numeral, check that the source follows a recognized convention instead of assuming every repeated-letter pattern is valid.',
                                  'family': 'text',
                                  'purpose': 'Roman Numeral Converter changes supported ordinary numbers into Roman numerals and can interpret valid Roman-numeral input where the page supports the reverse direction. It is useful for headings, dates, outlines and learning the notation.'},
 'scientific-calculator.html': {'caution': 'Browser numerical functions use finite floating-point precision and are not a substitute for certified engineering or laboratory software. Keep units with your working, confirm parentheses and mode settings, and follow the required significant-figure rules for formal work.',
                                'example': 'For a trigonometric problem, confirm whether the angle is in degrees or radians before evaluating a sine or cosine. A correct formula entered in the wrong angle mode can produce a completely different numerical answer.',
                                'family': 'calculator',
                                'purpose': 'Scientific Calculator adds functions such as powers, roots, logarithms or trigonometric operations beyond basic arithmetic. It is useful for study and technical calculations where operator order and angle mode need to be visible.'},
 'split-pdf.html': {'caution': 'Printed page labels inside a document can differ from the viewer’s numeric page positions, and forms, bookmarks, links or digital signatures may behave differently after extraction. Keep the original PDF until the new file and any advanced features are checked.',
                    'example': 'For a 10-page file, selecting pages 1-3 and 5 should create an output containing file pages 1, 2, 3 and 5. Open the result and verify the first page, last page and page count before sending it.',
                    'family': 'pdf',
                    'purpose': 'Split PDF extracts selected pages or ranges from a larger PDF into a new document. It is useful when only part of a report, statement or scanned file needs to be shared.'},
 'ssl-certificate-checker.html': {'caution': 'A valid certificate only proves that the TLS certificate passed certain checks for the connection; it does not make the website’s content trustworthy. Caching, load balancers, SNI and different network paths can also expose different certificates, so investigate the actual serving architecture when results conflict.',
                                  'example': 'After renewing a certificate, check the live hostname and compare the expiry and names with the certificate you expected to deploy. If a CDN or proxy terminates TLS, the public certificate may differ from the one installed on the origin server.',
                                  'family': 'network',
                                  'purpose': 'SSL Certificate Checker inspects certificate information that a website is serving so you can review fields such as hostname coverage and validity dates supported by the page. It is useful for diagnosing certificate deployment and renewal issues.'},
 'steam-playtime-calculator.html': {'caution': 'Steam-reported hours can include menus, idle time or sessions that do not represent active gameplay. Use the calculator for personal context rather than as proof of productivity, skill or exact time spent actively playing.',
                                    'example': 'If a game shows 300 total hours over roughly one year of active play, compare the average with the period you actually care about rather than dividing by an unrelated lifetime. The interpretation changes depending on whether you mean calendar days, active days or weeks.',
                                    'family': 'gaming',
                                    'purpose': 'Steam Playtime Calculator helps turn total playtime into averages or other easier-to-read comparisons supported by the page. It is useful for summarizing a game library or understanding what a large hour count means over a chosen period.'},
 'stopwatch.html': {'caution': 'Human button-press delay, device load, sleep mode and browser scheduling can affect measurements. Official competition, laboratory, medical or compliance timing should use equipment designed and calibrated for the required accuracy.',
                    'example': 'For repeated drills, define the same start and stop event each time, record several runs and compare them on the same device. Consistent procedure matters more than chasing one unusually fast result.',
                    'family': 'timer',
                    'purpose': 'Online Stopwatch measures elapsed time between a manual start and stop. It is convenient for practice runs, informal experiments and work intervals where browser-level timing is sufficient.'},
 'storage-size-converter.html': {'caution': 'Check whether the source uses decimal units (powers of 1000) or binary units (powers of 1024) before comparing capacity. Device manufacturers, operating systems and cloud services can label sizes differently, so keep the underlying bytes when precision matters.',
                                 'example': 'Convert a 1,024 MB value and compare the result under the unit convention the destination uses. Some systems use decimal multiples while others use binary multiples, which can make two labels appear different even when the underlying byte count is the same.',
                                 'family': 'calculator',
                                 'purpose': 'Storage Size Converter translates data-size units such as bytes, KB, MB, GB or related units supported by the page. It helps explain why a file size can look different across operating systems, drives and service dashboards.'},
 'text-case-converter.html': {'caution': 'Do not run passwords, code identifiers or other case-sensitive data through a converter unless changing case is intentional. Keep the original text when capitalization carries meaning, and perform a manual review before publishing.',
                              'example': 'Paste a heading written in all caps, convert it to title or sentence case, then review names, acronyms and brand spellings manually. Automatic case rules cannot always know which words are intentionally stylized.',
                              'family': 'text',
                              'purpose': 'Capitalization & Text Case Converter changes text between case styles such as upper, lower, title or sentence forms supported by the page. It is useful for cleaning headings, pasted lists and drafts without retyping every letter.'},
 'text-to-pdf.html': {'caution': 'A simple text-to-PDF export may not preserve advanced layout, accessibility tags, embedded fonts or document metadata required by professional publishing. Keep the original text and use a dedicated document editor when complex formatting or archival standards matter.',
                      'example': 'Paste the final text, review line breaks and headings, generate the PDF and reopen it before sending. Confirm that important characters, page breaks and readable margins appear as expected in the exported file.',
                      'family': 'pdf',
                      'purpose': 'Text to PDF creates a PDF document from text entered into the page. It is useful for turning a short note, draft or plain-text content into a shareable document that opens consistently across devices.'},
 'time-duration-calculator.html': {'caution': 'Time zones, daylight-saving transitions and unpaid breaks can change real-world duration calculations. Use a meeting planner or date-aware workflow when locations or date changes matter, and follow payroll or legal rules for official time records.',
                                   'example': 'From 09:35 to 12:10 the elapsed time is 2 hours 35 minutes. If the interval crosses midnight, make sure the tool or selected dates represent the next day rather than treating the end time as earlier on the same day.',
                                   'family': 'calculator',
                                   'purpose': 'Time Duration Calculator measures the elapsed time between two clock times or durations supported by the page. It is useful for work sessions, travel planning and schedules where crossing hour or day boundaries can make mental subtraction error-prone.'},
 'timezone-meeting-planner.html': {'caution': 'Time-zone offsets can change with daylight-saving rules and government decisions. Use named time zones and recheck important future meetings close to the date, especially when a schedule crosses a daylight-saving transition.',
                                   'example': 'Choose the participants’ real time zones, select a proposed time and review what that instant becomes for each location. Share the time with the time-zone labels or a calendar invitation rather than only saying “3 PM.”',
                                   'family': 'time',
                                   'purpose': 'Global & International Meeting Planner helps compare local clock times across selected time zones so a single meeting instant can be understood by people in different locations. It reduces manual offset arithmetic and daylight-saving mistakes.'},
 'typing-speed-test.html': {'caution': 'Text difficulty, keyboard layout, language familiarity, device latency and the exact WPM formula can affect scores. Treat the result as a practice metric rather than a standardized employment, medical or educational assessment unless the organization specifies this exact test.',
                            'example': 'Complete several tests with the same device and keyboard, then compare both words per minute and error rate. A faster score with many corrections may not represent better practical typing than a slightly slower but accurate result.',
                            'family': 'test',
                            'purpose': 'Typing Speed Test estimates typing rate and accuracy from the text entered during the timed exercise. It is useful for practice and personal comparison when the same test conditions are used consistently.'},
 'unit-converter.html': {'caution': 'Do not convert between different physical quantities without the extra information required, such as density. Engineering, medical and laboratory work may require exact definitions, significant figures and mandated rounding, so follow the governing standard for high-precision decisions.',
                         'example': 'Converting 2.5 kilometres to metres gives 2,500 metres because one kilometre equals 1,000 metres. Temperature conversions require a formula with an offset, which is why not every unit change can be handled by simple multiplication.',
                         'family': 'calculator',
                         'purpose': 'Unit Converter changes values between supported units that describe the same physical quantity. It is useful for everyday length, mass, temperature or other conversions when you keep the source and destination units explicit.'},
 'unix-timestamp-converter.html': {'caution': 'Time zones, daylight-saving display and timestamp unit are common sources of mistakes. Unix timestamps usually represent an instant independent of local time, so keep UTC available when comparing systems and confirm whether the source uses seconds, milliseconds or another precision.',
                                   'example': 'Check whether the source timestamp is in seconds or milliseconds before converting; the same digits interpreted with the wrong unit can produce a wildly different date. Compare the displayed UTC value with the intended local time when debugging an event.',
                                   'family': 'time',
                                   'purpose': 'Unix Timestamp Converter translates between Unix epoch values and human-readable date/time representations supported by the page. It is useful for logs, APIs and debugging systems that store time as seconds or milliseconds since the Unix epoch.'},
 'webp-to-jpg.html': {'caution': 'The output is a delivery copy rather than a better-quality master. Keep the original WebP, expect lossy compression in JPG, and compare real file size rather than assuming one format will always be smaller.',
                      'example': 'Convert the WebP, open the JPG and inspect transparent regions, small text and sharp edges before uploading it. If the source has transparency, verify the background used because JPEG cannot store a transparent channel.',
                      'family': 'image',
                      'purpose': 'WebP to JPG creates a JPEG compatibility copy for software or upload forms that do not accept WebP. It is most appropriate for photographic images where JPEG’s broad support is more important than WebP-specific features.'},
 'webp-to-png.html': {'caution': 'Changing to PNG does not recover detail already lost in the WebP source and can greatly increase file size. Keep the original WebP and choose PNG for compatibility, transparency or editing needs rather than as an automatic quality upgrade.',
                      'example': 'Convert a transparent WebP logo to PNG, then place the PNG over a contrasting background to confirm the transparent edges remain clean. Compare file size before using the new format on a performance-sensitive page.',
                      'family': 'image',
                      'purpose': 'WebP to PNG creates a PNG copy when a workflow needs PNG compatibility or preserved transparency supported by the source. PNG is lossless for the exported pixels but can be significantly larger than an efficiently encoded WebP.'},
 'website-reachability-checker.html': {'caution': 'One successful or failed request does not prove worldwide availability. CDNs, regional filtering, authentication, rate limits and network path differences can produce different results, so use multiple vantage points or the provider’s status page for serious incident diagnosis.',
                                       'example': 'Check the same URL in your browser and with the reachability tool. If the checker can reach it but your device cannot, local DNS, firewall, ISP or browser issues become more likely than a global outage.',
                                       'family': 'network',
                                       'purpose': 'Website Reachability Checker tests whether a target website can be reached through the method used by this page. It is useful for a quick status clue when you are unsure whether a site is responding from the checker’s network path.'},
 'whatsapp-link-generator.html': {'caution': 'Phone numbers are personal information and a public link can make a number easy to discover. The generated link starts a chat but does not verify the recipient’s identity, so obtain permission before publishing someone else’s number and review the final URL carefully.',
                                  'example': 'Enter the number with the correct country code, add the optional message, generate the link and test it on another device or private browser window. Confirm that both the recipient and pre-filled text are correct before publishing.',
                                  'family': 'developer',
                                  'purpose': 'WhatsApp Link Generator builds a click-to-chat URL from an international phone number and optional pre-filled message. It is useful for websites, QR codes and profiles where visitors should start a conversation without saving the number first.'},
 'word-counter.html': {'caution': 'Different editors can define words and characters differently around hyphens, apostrophes, emoji and non-Latin scripts. Use the destination service’s own counter for strict submission limits and treat this tool as a drafting aid.',
                       'example': 'Paste the final draft and compare both word and character totals with the destination limit. If a platform counts spaces, emojis or special characters differently, test the text in that platform before assuming the browser count will match exactly.',
                       'family': 'text',
                       'purpose': 'Word & Character Counter measures text length using the counting rules implemented by the page. It is useful for essays, social posts, forms and writing tasks that impose approximate word or character limits.'},
 'youtube-thumbnail-downloader.html': {'caution': 'A publicly accessible thumbnail is still protected by the rights associated with the video and image. Downloading does not grant permission to republish someone else’s artwork, and private, removed or unusual videos may not expose the expected thumbnail files.',
                                       'example': 'Paste a valid YouTube video URL or ID, load the available thumbnail and confirm it belongs to the intended video before saving or using it. Different videos may not provide every resolution variant.',
                                       'family': 'media',
                                       'purpose': 'YouTube Thumbnail Downloader & Viewer extracts thumbnail image URLs for a YouTube video so you can inspect or save an available thumbnail size. It is useful for your own videos, presentations and reference work where the thumbnail image is needed separately.'}}

def strip_tags(value: str) -> str:
    value = re.sub(r'<[^>]+>', ' ', value)
    value = html.unescape(value)
    return re.sub(r'\s+', ' ', value).strip()

def page_name(raw: str, filename: str) -> str:
    match = re.search(r'<h1\b[^>]*>(.*?)</h1>', raw, re.I | re.S)
    if match:
        name = strip_tags(match.group(1)).strip(' .')
        if name:
            return name
    return filename.rsplit('.', 1)[0].replace('-', ' ').title()

def render(name: str, item: dict[str, str]) -> str:
    steps = [value.format(name=name) for value in FAMILY_STEPS[item['family']]]
    parts = [
        START,
        '<section class="section" data-nexusnova-tool-guide><div class="container article">',
        f'<h2>{html.escape(name)}: clear guide for real use</h2>',
        f'<p>{html.escape(item["purpose"])}</p>',
        f'<h3>How to use {html.escape(name)}</h3>',
        '<ol>' + ''.join(f'<li>{html.escape(step)}</li>' for step in steps) + '</ol>',
        '<h3>Practical example</h3>',
        f'<p>{html.escape(item["example"])}</p>',
        '<h3>Limits, privacy and checks</h3>',
        f'<p>{html.escape(item["caution"])}</p>',
        '</div></section>',
        END,
    ]
    return '\n'.join(parts) + '\n'

def apply(path: Path, item: dict[str, str]) -> bool:
    raw = path.read_text(encoding='utf-8')
    name = page_name(raw, path.name)
    block = render(name, item)
    if START in raw:
        updated, count = re.subn(re.escape(START) + r'.*?' + re.escape(END) + r'\n?', block, raw, count=1, flags=re.S)
        if count != 1:
            raise RuntimeError(f'Unable to replace guide block in {path.name}')
    else:
        positions = list(re.finditer(r'</main\s*>', raw, re.I))
        if not positions:
            raise RuntimeError(f'Missing </main> in {path.name}')
        pos = positions[-1].start()
        updated = raw[:pos] + block + raw[pos:]
    if updated == raw:
        return False
    path.write_text(updated, encoding='utf-8')
    return True

def main() -> None:
    missing = [name for name in CONTENT if not (ROOT / name).exists()]
    if missing:
        raise SystemExit('Missing targets: ' + ', '.join(missing))
    changed = []
    for filename, item in CONTENT.items():
        path = ROOT / filename
        if apply(path, item):
            changed.append(filename)
            print('Deepened', filename)
    CHANGED.write_text('\n'.join(changed) + ('\n' if changed else ''), encoding='utf-8')
    print('Tool guide targets:', len(CONTENT))
    print('Changed pages:', len(changed))

if __name__ == '__main__':
    main()
